/*
-- Query: SELECT * FROM zgwqhx5rlwm7kj0u.quiz
LIMIT 0, 1000

-- Date: 2022-10-30 18:57
*/
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (3,'beginner','JavaScript','Inside which HTML element do we put the JavaScript?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (4,'beginner','JavaScript','What is the correct JavaScript syntax to change the content of the HTML element below: <p id=\"demo\">This is a demonstration.</p>');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (5,'beginner','JavaScript','Where is the correct place to insert a JavaScript?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (6,'beginner','JavaScript','What is the correct syntax for referring to an external script called \"xxx.js\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (7,'beginner','JavaScript','The external JavaScript file must contain the <script> tag.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (8,'beginner','JavaScript','How do you write \"Hello World\" in an alert box?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (9,'beginner','JavaScript','How do you create a function in JavaScript?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (10,'beginner','JavaScript','How do you call a function named \"myFunction\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (11,'beginner','JavaScript','How to write an IF statement in JavaScript?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (12,'beginner','JavaScript','How to write an IF statement for executing some code if \"i\" is NOT equal to 5?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (13,'beginner','JavaScript','How does a WHILE loop start?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (14,'beginner','JavaScript','How does a FOR loop start?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (15,'beginner','JavaScript','How can you add a comment in a JavaScript?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (16,'beginner','JavaScript','How to insert a comment that has more than one line?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (17,'beginner','JavaScript','What is the correct way to write a JavaScript array?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (18,'beginner','JavaScript','How do you round the number 7.25, to the nearest integer?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (19,'beginner','JavaScript','How do you find the number with the highest value of x and y?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (20,'beginner','JavaScript','What is the correct JavaScript syntax for opening a new window called \"w2\" ?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (21,'beginner','JavaScript','JavaScript is the same as Java.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (22,'beginner','JavaScript','How can you detect the client\'s browser name?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (23,'beginner','JavaScript','Which event occurs when the user clicks on an HTML element?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (24,'beginner','JavaScript','How do you declare a JavaScript variable?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (25,'beginner','JavaScript','Which operator is used to assign a value to a variable?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (26,'beginner','JavaScript','What will the following code return: Boolean(10 > 9)');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (27,'beginner','JavaScript','Is JavaScript case-sensitive?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (28,'beginner','HTML','What does HTML stand for?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (29,'beginner','HTML','Who is making the Web standards?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (30,'beginner','HTML','Choose the correct HTML element for the largest heading:');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (31,'beginner','HTML','What is the correct HTML element for inserting a line break?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (32,'beginner','HTML','What is the correct HTML for adding a background color?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (33,'beginner','HTML','Choose the correct HTML element to define important text');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (34,'beginner','HTML','Choose the correct HTML element to define emphasized text');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (35,'beginner','HTML','What is the correct HTML for creating a hyperlink?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (36,'beginner','HTML','Which character is used to indicate an end tag?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (37,'beginner','HTML','How can you open a link in a new tab/browser window?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (38,'beginner','HTML','Which of these elements are all <table> elements?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (39,'beginner','HTML','Inline elements are normally displayed without starting a new line.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (40,'beginner','HTML','How can you make a numbered list?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (41,'beginner','HTML','How can you make a bulleted list?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (42,'beginner','HTML','What is the correct HTML for making a checkbox?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (43,'beginner','HTML','What is the correct HTML for making a text input field?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (44,'beginner','HTML','What is the correct HTML for making a drop-down list?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (45,'beginner','HTML','What is the correct HTML for making a text area?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (46,'beginner','HTML','What is the correct HTML for inserting an image?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (47,'beginner','HTML','What is the correct HTML for inserting a background image?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (48,'beginner','HTML','An <iframe> is used to display a web page within a web page.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (49,'beginner','HTML','HTML comments start with <!-- and end with -->');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (50,'beginner','HTML','Block elements are normally displayed without starting a new line.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (51,'beginner','HTML','Which HTML element defines the title of a document?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (52,'beginner','HTML','Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (53,'beginner','HTML','Which doctype is correct for HTML5?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (54,'beginner','HTML','Which HTML element is used to specify a footer for a document or section?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (55,'beginner','HTML','In HTML, you can embed SVG elements directly into an HTML page.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (56,'beginner','HTML','What is the correct HTML element for playing video files?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (57,'beginner','HTML','What is the correct HTML element for playing audio files?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (58,'beginner','HTML','The HTML global attribute, \"contenteditable\" is used to:');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (59,'beginner','HTML','In HTML, onblur and onfocus are:');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (60,'beginner','HTML','Graphics defined by SVG is in which format?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (61,'beginner','HTML','The HTML <canvas> element is used to:');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (62,'beginner','HTML','In HTML, which attribute is used to specify that an input field must be filled out?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (63,'beginner','HTML','Which input type defines a slider control?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (64,'beginner','HTML','Which HTML element is used to display a scalar measurement within a range?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (65,'beginner','HTML','Which HTML element defines navigation links?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (66,'beginner','HTML','In HTML, what does the <aside> element define?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (67,'beginner','HTML','Which HTML element is used to specify a header for a document or section?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (68,'beginner','CSS','What does CSS stand for?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (69,'beginner','CSS','What is the correct HTML for referring to an external style sheet?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (70,'beginner','CSS','Where in an HTML document is the correct place to refer to an external style sheet?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (71,'beginner','CSS','Which HTML tag is used to define an internal style sheet?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (72,'beginner','CSS','Which HTML attribute is used to define inline styles?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (73,'beginner','CSS','Which is the correct CSS syntax?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (74,'beginner','CSS','How do you insert a comment in a CSS file?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (75,'beginner','CSS','Which property is used to change the background color?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (76,'beginner','CSS','How do you add a background color for all <h1> elements?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (77,'beginner','CSS','Which CSS property is used to change the text color of an element?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (78,'beginner','CSS','Which CSS property controls the text size?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (79,'beginner','CSS','What is the correct CSS syntax for making all the <p> elements bold?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (80,'beginner','CSS','How do you display hyperlinks without an underline?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (81,'beginner','CSS','How do you make each word in a text start with a capital letter?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (82,'beginner','CSS','Which property is used to change the font of an element?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (83,'beginner','CSS','How do you make the text bold?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (84,'beginner','CSS','Which property is used to change the left margin of an element?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (85,'beginner','CSS','When using the padding property; are you allowed to use negative values?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (86,'beginner','CSS','How do you make a list that lists its items with squares?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (87,'beginner','CSS','How do you select an element with id \"demo\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (88,'beginner','CSS','How do you select elements with class name \"test\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (89,'beginner','CSS','How do you select all p elements inside a div element?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (90,'beginner','CSS','How do you group selectors?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (91,'beginner','CSS','What is the default value of the position property?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (92,'beginner','Git','What is Git?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (93,'beginner','Git','Git is the same as GitHub.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (94,'beginner','Git','What is the command to get the installed version of Git?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (95,'beginner','Git','Which option should you use to set the default user name for every repository on your computer?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (96,'beginner','Git','What is the command to set the user email for the current repository?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (97,'beginner','Git','What is the command to add all files and changes of the current folder to the staging environment of the Git repository?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (98,'beginner','Git','What is the command to get the current status of the Git repository?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (99,'beginner','Git','What is the command to initialize Git on the current repository?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (100,'beginner','Git','Git automatically adds new files to the repository and starts tracking them.');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (101,'beginner','Git','Git commit history is automatically deleted:');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (102,'beginner','Git','What is the command to commit the staged changes for the Git repository?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (103,'beginner','Git','What is the command to commit with the message \"New email\":');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (104,'beginner','Git','What is the command to view the history of commits for the repository?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (105,'beginner','Git','What is the command to see the available options for the commit command?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (106,'beginner','Git','In Git, a branch is:');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (107,'beginner','Git','What is the command to create a new branch named \"new-email\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (108,'beginner','Git','What is the command to move to the branch named \"new-email\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (109,'beginner','Git','What is the option, when moving to a branch, to create the branch it if it does not exist?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (110,'beginner','Git','What is the command to merge the current branch with the branch \"new-email\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (111,'beginner','Git','What is the command to delete the branch \"new-email\"');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (112,'beginner','Git','What is the command to add the remote repository \"https://abc.xyz/d/e.git\" as \"origin\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (113,'beginner','Git','What is the command to push the current repository to the remote origin?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (114,'beginner','Git','What is the command to get all the change history of the remote repository \"origin\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (115,'beginner','Git','What is the command to show the differences between the current branch and the branch \"new-email\"?');
INSERT INTO `` (`Id`,`level`,`subject`,`question`) VALUES (116,'beginner','Git','Git Pull is a combination of:');
